name: Build for Windows

on:
push:
branches: \[ main ]
workflow\_dispatch:

jobs:
build\_windows:
runs-on: windows-latest

```
steps:
  - name: Checkout code
    uses: actions/checkout@v4

  - name: Cache pip dependencies
    uses: actions/cache@v3
    with:
      path: ~/.cache/pip
      key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
      restore-keys: |
        ${{ runner.os }}-pip-

  - name: Set up Python
    uses: actions/setup-python@v4
    with:
      python-version: '3.10'

  - name: Install dependencies
    run: |
      python -m pip install --upgrade pip==23.2.1 wheel setuptools
      pip install --retries 3 --timeout 30 -e .
      pip install pyinstaller==5.13.0

  - name: Run Linter
    run: |
      pip install flake8
      flake8 .

  - name: Run Tests
    run: |
      python -m unittest discover tests

  - name: Build executable
    run: pyinstaller --onefile --name OffloadHelper main.py

  - name: Upload artifact
    uses: actions/upload-artifact@v4
    with:
      name: offloadhelper-windows-exe-${{ github.run_number }}-${{ github.sha }}
      path: dist/OffloadHelper.exe
```
