# .github/workflows/build-windows.yml

name: Build Windows Release

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build_windows:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        shell: pwsh
        run: |
          python -m pip install --upgrade pip wheel setuptools pyinstaller
          if (Test-Path requirements.txt) {
            pip install -r requirements.txt
          } else {
            pip install -e .
          }

      - name: Build Windows executable
        shell: pwsh
        run: pyinstaller --onefile --name OffloadHelper main.py

      - name: Upload Windows artifact
        uses: actions/upload-artifact@v4
        with:
          name: offloadhelper-windows
          path: dist/OffloadHelper.exe
