name: Build Release Binaries

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        python-version: [3.10]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip==23.2.1 wheel setuptools
          pip install --retries 3 --timeout 30 -e .
          pip install pyinstaller==5.13.0

      - name: Run Linter
        run: |
          pip install flake8
          flake8 .

      - name: Run Tests
        run: python -m unittest discover tests

      - name: Build executable
        run: |
          if [ "${{ matrix.os }}" == "windows-latest" ]; then
            pyinstaller --onefile --name OffloadHelper main.py
          elif [ "${{ matrix.os }}" == "ubuntu-latest" ]; then
            pyinstaller --onefile --name offloadhelper_linux main.py
          elif [ "${{ matrix.os }}" == "macos-latest" ]; then
            pyinstaller --onefile --name offloadhelper_macos main.py
          fi

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: offloadhelper-${{ matrix.os }}-${{ github.run_number }}-${{ github.sha }}
          path: |
            dist/OffloadHelper.exe
            dist/offloadhelper_linux
            dist/offloadhelper_macos
